default: &default
  adapter: postgresql
  encoding: unicode
 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: postgresql://postgres@localhost:45431

development:
  <<: *default
  database: rainbot_development

test:
  <<: *default
  database: rainbot_test

production:
  <<: *default
  database: rainbot_production
  username: rainbot
  password: <%= ENV['RAINBOT_DATABASE_PASSWORD'] %>
